#!/usr/bin/bash
#
# Put customizations to your image in this file.

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Munin plugins
MUNIN_PLUGINS="
	nginx_request
	nginx_status
"

# Exit if any commands fail
set -o errexit

echo "* Add nginx ssl folder"
mkdir -p /opt/local/etc/nginx/ssl

echo "* Remove pgsql folder after installation"
rm -rf /var/pgsql

echo "* Create sogo log directories"
mkdir -p /var/log/sogo /var/spool/sogo
chown sogo:sogo /var/log/sogo /var/spool/sogo

echo "* Install sogo-user-import"
npm install -g sogo-user-import

echo "* Activate munin plugins"
/opt/core/bin/munin-node-plugins ${MUNIN_PLUGINS}

echo "* Cleanup home/admin because of delegate dataset usage"
rm -rf /home/admin/.[^.]*

echo "* Cleaning up."
rm -rf /root/*
sm-prepare-image -y
